version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8085:8085"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  warp-network:
    driver: bridge