version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8085:8085
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=ganymede
    depends_on:
      - redis
    
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    environment:
      - REDIS_PASSWORD=ganymede
    command: redis-server --requirepass ganymede